name: AuthenticItem
main: net.loadingchunks.plugins.AuthenticItem.AuthenticItem.AuthenticItem
version: 0.1

commands:
   authentic:
      description: Marks a special trait on an item.
      usage: /authentic <type>